I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    image post apocalyptic = post_apocalyptic.jpg
  File "game/script.rpy", line 8, in <module>
    image post apocalyptic = post_apocalyptic.jpg
NameError: name 'post_apocalyptic' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script
    image post apocalyptic = post_apocalyptic.jpg
  File "C:\Users\charles\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 920, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\charles\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 8, in <module>
    image post apocalyptic = post_apocalyptic.jpg
NameError: name 'post_apocalyptic' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
apocalypse 1.0
Sat Nov 30 14:54:17 2024
